= Unofficial DaVinci Resolve Scripting Documentation
:icons: font
:toc:


== Basic Resolve API

=== Resolve

[options="header"]
|===
| Method               | Return Type | Comment
| `Fusion()`           | `Fusion` | Returns the Fusion object. Starting point for Fusion scripts.
| `GetMediaStorage()`  | `MediaStorage` | Returns media storage object to query and act on media locations.
| `GetProjectManager()`| `ProjectManager` | Returns project manager object for currently open database.
| `OpenPage(pageName)` | `None` |  Switches to indicated page in DaVinci Resolve. Input can be one of ("media", "cut", "edit", "fusion", "color", "fairlight", "deliver").
|===


=== ProjectManager

[options="header"]
|===
| Method                                  | Return Type        | Comment
|`CreateProject(projectName)`             |`Project`           | Creates and returns a project if projectName (text) is unique, and None if it is not.
|`DeleteProject(projectName)`             |`Bool`              | Delete project in the current folder if not currently loaded.
|`LoadProject(projectName)`               |`Project`           | Loads and returns the project with name = projectName (text) if there is a match found, and None if there is no matching Project.
|`GetCurrentProject()`                   |`Project`            | Returns the currently loaded Resolve project.
|`SaveProject()`                         |`Bool`               | Saves the currently loaded project with its own name. Returns True if successful.
|`CloseProject(project)`                 |`Bool`               | Closes the specified project without saving.
|`CreateFolder(folderName)`              |`Bool`               | Creates a folder if folderName (text) is unique.
|`GetProjectListInCurrentFolder()`       |`[project names...]` | Returns a list of project names in current folder.
|`GetFolderListInCurrentFolder()`        |`[folder names...]`  | Returns a list of folder names in current folder.
|`GotoRootFolder()`                      |`Bool`               | Opens root folder in database.
|`GotoParentFolder()`                    |`Bool`               | Opens parent folder of current folder in database if current folder has parent.
|`OpenFolder(folderName)`                |`Bool`               | Opens folder under given name.
|`ImportProject(filePath)`               |`Bool`               | Imports a project under given file path. Returns true in case of success.
|`ExportProject(projectName, filePath)`  |`Bool`               | Exports a project based on given name into provided file path. Returns true in case of success.
|`RestoreProject(filePath)`              |`Bool`               | Restores a project under given backup file path. Returns true in case of success.
|===

== Project

[options="header"]
|===
| Method                                               | Return Type        | Comment
|`GetMediaPool()`                                      |`MediaPool`         | Returns the Media Pool object.
|`GetTimelineCount()`                                  |`int`               | Returns the number of timelines currently present in the project.
|`GetTimelineByIndex(idx)`                             |`Timeline`          | Returns timeline at the given index, 1 <= idx <= project.GetTimelineCount()
|`GetCurrentTimeline()`                                |`Timeline`          | Returns the currently loaded timeline.
|`SetCurrentTimeline(timeline)`                        |`Bool`              | Sets given timeline as current timeline for the project. Returns True if successful.
|`GetName()`                                           |`string`            | Returns project name.
|`SetName(projectName)`                                |`Bool`              | Sets project name if given projectname (text) is unique.
|`GetPresetList()`                                     |`[presets...]`      | Returns a list of presets and their information.
|`SetPreset(presetName)`                               |`Bool`              | Sets preset by given presetName (string) into project.
|`GetRenderJobList()`                                  |`[render jobs...]`  | Returns a list of render jobs and their information.
|`GetRenderPresetList()`                               |`[presets...]`      | Returns a list of render presets and their information.
|`StartRendering(index1, index2, ...)`                 |`Bool`              | Starts rendering for given render jobs based on their indices.
|`StartRendering([idxs...], isInteractiveMode = False)`|`Bool`              | Starts rendering for given render jobs based on their indices. Optional field `isInteractiveMode`. It is Bool Type and it defaults to False. `isInteractiveMode` indicates whether there should be display of error dialog during rendering.
|`StartRendering(isInteractiveMode = False)`           |`Bool`              | Starts rendering for all render jobs. Optional field `isInteractiveMode`. It is Bool Type and it defaults to False. `isInteractiveMode` indicates whether there should be display of error dialog during rendering.
|`StopRendering()`                                     | `None`             | Stops rendering for all render jobs.
|`IsRenderingInProgress()`                             | `Bool`             | Returns true is rendering is in progress.
|`AddRenderJob()`                                      | `Bool`             | Adds render job to render queue.
|`DeleteRenderJobByIndex(idx)`                         | `Bool`             | Deletes render job based on given job index (int).
|`DeleteAllRenderJobs()`                               | `Bool`             | Deletes all render jobs.
|`LoadRenderPreset(presetName)`                        | `Bool`             | Sets a preset as current preset for rendering if presetName (text) exists.
|`SaveAsNewRenderPreset(presetName)`                   | `Bool`             | Creates a new render preset by given name if presetName(text) is unique.
|`SetRenderSettings({settings})`                       | `Bool`             | Sets given settings for rendering. Settings is a dict, with support for the keys: `"SelectAllFrames", "MarkIn", "MarkOut", "TargetDir", "CustomName"`.
|`GetRenderJobStatus(idx)`                             | `{status info}`      | Returns a dict with job status and completion percentage of the job by given job index (int).
|`GetSetting(settingName)`                             | `string`             | Returns value of project setting (indicated by settingName, string). Check the section below for more information.
|`SetSetting(settingName, settingValue)`               | `Bool`               | Sets a project setting (indicated by settingName, string) to the value (settingValue, string). Check the section below for more information.
|`GetRenderFormats()`                                  | `{render formats..}` | Returns a dict (format -> file extension) of available render formats.
|`GetRenderCodecs(renderFormat)`                       | `{render codecs...}` | Returns a dict (codec description -> codec name) of available codecs for given render format (string).
|`GetCurrentRenderFormatAndCodec()`                    | `{format, codec}`    | Returns a dict with currently selected format 'format' and render codec 'codec'.
|`SetCurrentRenderFormatAndCodec(format, codec)`       | `Bool`               | Sets given render format (string) and render codec (string) as options for rendering.



== About This Document
This document is a formatted copy of the official BlackmagicDesign DaVinci Resolve scripting documentation. +


WARNING: Keep in mind that this document might contain errors and might not be up to date with the current Resolve version. +
If in doubt, always consult the official Resolve documentation provided by BlackmagicDesign.


<<<


In this package, you will find a brief introduction to the Scripting API for DaVinci Resolve Studio. Apart from this README.txt file, this package contains folders containing the basic import
modules for scripting access (DaVinciResolve.py) and some representative examples.

From v16.2.0 onwards, the nodeIndex parameters accepted by SetLUT() and SetCDL() are 1-based instead of 0-based, i.e. 1 <= nodeIndex <= total number of nodes.



== Overview

As with Blackmagic Design Fusion scripts, user scripts written in Lua and Python programming languages are supported. By default, scripts can be invoked from the Console window in the Fusion page,
or via command line. This permission can be changed in Resolve Preferences, to be only from Console, or to be invoked from the local network. Please be aware of the security implications when
allowing scripting access from outside of the Resolve application.

== Using a script

DaVinci Resolve needs to be running for a script to be invoked.

For a Resolve script to be executed from an external folder, the script needs to know of the API location.
You may need to set the these environment variables to allow for your Python installation to pick up the appropriate dependencies as shown below:

Mac OS X:
----
RESOLVE_SCRIPT_API="/Library/Application Support/Blackmagic Design/DaVinci Resolve/Developer/Scripting/"
RESOLVE_SCRIPT_LIB="/Applications/DaVinci Resolve/DaVinci Resolve.app/Contents/Libraries/Fusion/fusionscript.so"
PYTHONPATH="$PYTHONPATH:$RESOLVE_SCRIPT_API/Modules/"
----

Windows:
----
RESOLVE_SCRIPT_API="%PROGRAMDATA%\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\"
RESOLVE_SCRIPT_LIB="C:\Program Files\Blackmagic Design\DaVinci Resolve\fusionscript.dll"
PYTHONPATH="%PYTHONPATH%;%RESOLVE_SCRIPT_API%\Modules\"
----

Linux:
----
RESOLVE_SCRIPT_API="/opt/resolve/Developer/Scripting/"
RESOLVE_SCRIPT_LIB="/opt/resolve/libs/Fusion/fusionscript.so"
PYTHONPATH="$PYTHONPATH:$RESOLVE_SCRIPT_API/Modules/"
(Note: For standard ISO Linux installations, the path above may need to be modified to refer to /home/resolve instead of /opt/resolve)
----

As with Fusion scripts, Resolve scripts can also be invoked via the menu and the Console.

On startup, DaVinci Resolve scans the Utility Scripts directory and enumerates the scripts found in the Script application menu. Placing your script in this folder and invoking it from this menu is
the easiest way to use scripts. The Utility Scripts folder is located in:
----
Mac OS X:   /Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Comp/
Windows:    %APPDATA%\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Comp\
Linux:      /opt/resolve/Fusion/Scripts/Comp/   (or /home/resolve/Fusion/Scripts/Comp/ depending on installation)
----

The interactive Console window allows for an easy way to execute simple scripting commands, to query or modify properties, and to test scripts. The console accepts commands in Python 2.7, Python 3.6
and Lua and evaluates and executes them immediately. For more information on how to use the Console, please refer to the DaVinci Resolve User Manual.

.This example Python script creates a simple project:
[source, Python]
----
#!/usr/bin/env python
import DaVinciResolveScript as dvr_script
resolve = dvr_script.scriptapp("Resolve")
fusion = resolve.Fusion()
projectManager = resolve.GetProjectManager()
projectManager.CreateProject("Hello World")
----

The resolve object is the fundamental starting point for scripting via Resolve. As a native object, it can be inspected for further scriptable properties - using table iteration and "getmetatable"
in Lua and dir, help etc in Python (among other methods). A notable scriptable object above is fusion - it allows access to all existing Fusion scripting functionality.


== Running DaVinci Resolve in headless mode

DaVinci Resolve can be launched in a headless mode without the user interface using the -nogui command line option. When DaVinci Resolve is launched using this option, the user interface is disabled.
However, the various scripting APIs will continue to work as expected.



== List and Dict Data Structures
Beside primitive data types, Resolve's Python API mainly uses list and dict data structures. Lists are denoted by [ ... ] and dicts are denoted by { ... } above.
As Lua does not support list and dict data structures, the Lua API implements "list" as a table with indices, e.g. { [1] = listValue1, [2] = listValue2, ... }.
Similarly the Lua API implements "dict" as a table with the dictionary key as first element, e.g. { [dictKey1] = dictValue1, [dictKey2] = dictValue2, ... }.


== Looking up Project and Clip properties

This section covers additional notes for the functions "Project:GetSetting", "Project:SetSetting", "MediaPoolItem:GetClipProperty" and "MediaPoolItem:SetClipProperty". These functions are used to get
and set properties otherwise available to the user through the Project Settings and the Clip Attributes dialogs.

The functions follow a key-value pair format, where each property is identified by a key (the settingName or propertyName parameter) and possesses a value (typically a text value). Keys and values are
designed to be easily correlated with parameter names and values in the Resolve UI. Explicitly enumerated values for some parameters are listed below.

Some properties may be read only - these include intrinsic clip properties like date created or sample rate, and properties that can be disabled in specific application contexts (e.g. custom colorspaces
in an ACES workflow, or output sizing parameters when behavior is set to match timeline)

=== Getting Values
Invoke `Project:GetSetting` or "MediaPoolItem:GetClipProperty" with the appropriate property key. To get a snapshot of all queryable properties (keys and values), you can call "Project:GetSetting" or
"MediaPoolItem:GetClipProperty" without parameters (or with a NoneType or a blank property key). Using specific keys to query individual properties will be faster. Note that getting a property using an
invalid key will return a trivial result.

=== Setting Values
Invoke "Project:SetSetting" or "MediaPoolItem:SetClipProperty" with the appropriate property key and a valid value. When setting a parameter, please check the return value to ensure the success of the
operation. You can troubleshoot the validity of keys and values by setting the desired result from the UI and checking property snapshots before and after the change.

.The following Project properties have specifically enumerated values:
superScale::
The property value is an enumerated integer between 0 and 3 with these meanings: 0=Auto, 1=no scaling, and 2, 3 and 4 represent the Super Scale multipliers 2x, 3x and 4x. +
Affects:
* x = Project:GetSetting('superScale') and Project:SetSetting('superScale', x)

timelineFrameRate::
The property value is one of the frame rates available to the user in project settings under "Timeline frame rate" option. Drop Frame can be configured for supported frame rates by appending the frame rate with "DF", e.g. "29.97 DF" will enable drop frame and "29.97" will disable drop frame +
Affects:
* x = Project:GetSetting('timelineFrameRate') and Project:SetSetting('timelineFrameRate', x)


.The following Clip properties have specifically enumerated values:
superScale:: The property value is an enumerated integer between 1 and 3 with these meanings: 1=no scaling, and 2, 3 and 4 represent the Super Scale multipliers 2x, 3x and 4x.
Affects:
* x = MediaPoolItem:GetClipProperty('Super Scale') and MediaPoolItem:SetClipProperty('Super Scale', x)
